management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      show-details: always

api:
  nombre: CerberoBeta-Store-Wize
  mensaje-error-default: "Lo sentimos, por el momento no podemos realizar su operaci\u00f3n"
  codigo-error-default: 1
  mensajes-error:
    002: "El servidor no pudo interpretar la solicitud dada una sintaxis invalida."

spring:
  application:
    name: ms-storewize
  main:
    banner-mode: off
  profiles:
    active: local
  h2:
    console:
      enabled: true
  datasource:
    url:  jdbc:h2:mem:test
    username: root


server:
  port: 8080
  servlet:
    context-path: /cerberobeta/store/products

apireststore:
  timeout: 10000
  url:
    products: https://fakestoreapi.com/products
    categories: https://fakestoreapi.com/products/categories
    users: https://fakestoreapi.com/users/